name: smoke
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: CraftOS-PC smoke
        uses: Commandcracker/craftos-pc-action@v1
        with:
          root: ./
          timeout: "15"
          options: --script /github/workspace/dev/smoke.lua
